project:
  type: book

book:
  title: "Foundations of Vision (2nd Edition)"
  author: "Brian Wandell"
  date: "10/26/2024"
  chapters:
    - index.qmd
    - part: "Image Encoding"
      chapters:
       - chapters/part-1-image-encoding-v2.qmd
       - chapters/chapter-2-image-formation-v2.qmd
       - chapters/chapter-3-the-photoreceptor-mosaic-v2.qmd
       - chapters/chapter-4-wavelength-encoding-v2.qmd
    - part:  "Image Representation"
      chapters:
      - chapters/part-2-image-representation-v2.qmd
      - chapters/chapter-5-the-retinal-representation-v2.qmd
      - chapters/chapter-6-the-cortical-representation-v2.qmd
      - chapters/chapter-7-pattern-sensitivity-v2.qmd
      - chapters/chapter-8-multiresolution-image-representations-v2.qmd
    - part: "Image Interpretation"
      chapters:
       - chapters/part-3-image-interpretation-v2.qmd
       - chapters/chapter-9-color-v2.qmd
       - chapters/chapter-10-motion-and-depth-v2.qmd
       - chapters/chapter-11-seeing-v2.qmd
    - references.qmd
    - part: "Appendix"
      chapters:
       - chapters/appendix-v2.qmd
       - chapters/appendix-computational-examples-v2.qmd
       - chapters/appendix-online-teaching-resources-v2.qmd

bibliography: paperpile.bib

crossref:
  chapters: true
  fig-prefix: "Figure"
  tbl-prefix: "Table"
  sec-prefix: "Section"
  
#  I am unsure about these formatting commands for the document.  Experimental.
format:
  html:
    toc: true
    layout: sidebar
    number-sections: true
    theme: cosmo   # flatly, yeti, sandstone, minty, cerulean, default
    fig-cap-location: margin
    render-on-save: true
    mathjax: "local"
    math: 
      number-sections: true
      number-equations: true
  pdf:
    documentclass: scrreprt
    toc: true
    toc-title: "Contents"
    toc-number-sections: true
    toc-number-depth: 2
    fig-caption: true
    number-sections: true
    number-depth: 2
    math:
      number-equations: true





